// lib/clients.mjs — one place that decides real client vs. stub.
//
// Provisional rails for Run A (P1.1). The Backend agent (Stage 3) owns the real
// Anthropic and Voyage clients; this file exists so nothing downstream has to be
// rewritten when they land — only the two `TODO(Stage 3)` bodies get replaced.
//
// Design rule: a stub must never activate silently. Answer accuracy is this
// project's #1 stated risk, and a scored run that unknowingly graded canned text
// is worse than a run that failed outright. So stubs are opt-in, announce
// themselves once, and are recorded for later assertion via usedMocks().

import { createClient } from '@supabase/supabase-js';
import { createHash } from 'node:crypto';

const STUBS_ALLOWED = process.env.ALLOW_STUBS === 'true';
const used = new Set();
const announced = new Set();

function announce(name) {
  used.add(name);
  if (announced.has(name)) return;
  announced.add(name);
  console.warn(
    `\n  ⚠  STUB ACTIVE: ${name} is returning fabricated data.\n` +
    `     Nothing produced from it is a real result. Set ${name.toUpperCase()}_API_KEY\n` +
    `     in .env to use the real service. See SETUP-BLOCKERS.md.\n`
  );
}

/** Names of every stub exercised this process. Stage 5/5.5 must assert this is empty. */
export function usedMocks() {
  return [...used];
}

function require_(name) {
  const v = process.env[name];
  if (!v) throw new Error(`Missing ${name}. Run with --env-file=.env, or see .env.example.`);
  return v;
}

// ---------------------------------------------------------------------------
// Supabase — real, and the only client wired to a live service in Run A.
// ---------------------------------------------------------------------------

/**
 * Server-side client. Uses service_role, which bypasses row-level security —
 * never import this from anything that ships to the device.
 */
export function supabaseAdmin() {
  return createClient(
    require_('EXPO_PUBLIC_SUPABASE_URL'),
    require_('SUPABASE_SERVICE_ROLE_KEY'),
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}

// ---------------------------------------------------------------------------
// Voyage — stubbed. Interface mirrors the real embeddings call.
// ---------------------------------------------------------------------------

// voyage-3-large default width. Stage 2.5 confirms the model and re-embeds if
// this is wrong — the stored vector width must match the live model exactly.
export const EMBED_DIM = 1024;

/**
 * @param {string[]} texts
 * @returns {Promise<{embeddings: number[][], model: string, stub: boolean}>}
 */
export async function embed(texts) {
  if (process.env.VOYAGE_API_KEY) {
    throw new Error('TODO(Stage 3): real Voyage client not implemented — key is set but unused.');
  }
  if (!STUBS_ALLOWED) {
    throw new Error(
      'VOYAGE_API_KEY is empty. Set it, or pass ALLOW_STUBS=true to run against the stub.'
    );
  }
  announce('voyage');

  // Deterministic from content, so the same chunk embeds identically across runs
  // and idempotency tests mean something. Cosine-normalised. Carries no semantics
  // whatsoever — retrieval quality measured against this is noise, by design.
  const embeddings = texts.map((t) => {
    const seed = createHash('sha256').update(t).digest();
    const v = Array.from({ length: EMBED_DIM }, (_, i) => (seed[i % seed.length] - 127.5) / 127.5);
    const norm = Math.hypot(...v) || 1;
    return v.map((x) => x / norm);
  });

  return { embeddings, model: 'stub-not-a-real-model', stub: true };
}

// ---------------------------------------------------------------------------
// Anthropic — stubbed. Interface mirrors messages.create.
// ---------------------------------------------------------------------------

/**
 * @param {{system?: string, messages: {role: string, content: string}[]}} args
 * @returns {Promise<{text: string, model: string, stub: boolean}>}
 */
export async function complete({ messages }) {
  if (process.env.ANTHROPIC_API_KEY) {
    throw new Error('TODO(Stage 3): real Anthropic client not implemented — key is set but unused.');
  }
  if (!STUBS_ALLOWED) {
    throw new Error(
      'ANTHROPIC_API_KEY is empty. Set it, or pass ALLOW_STUBS=true to run against the stub.'
    );
  }
  announce('anthropic');

  const last = messages.at(-1)?.content ?? '';
  return {
    text:
      `[STUB RESPONSE — not generated by Claude, contains no real diagnostic guidance]\n` +
      `Received ${last.length} characters. The round trip works; the answer does not exist yet.`,
    model: 'stub-not-a-real-model',
    stub: true,
  };
}
