// scripts/sync-app-env.mjs — generate app/.env from the root .env.
//
// Expo's CLI reads .env from its own project directory, which is app/. Rather than
// keep two hand-maintained files that drift, this derives one from the other and
// copies ONLY keys prefixed EXPO_PUBLIC_.
//
// That filter is the point. Expo inlines every EXPO_PUBLIC_ var into the shipped
// bundle, so a server-side secret that reaches app/.env would reach the device.
// Here it cannot: the prefix is the allowlist, and anything else is dropped and
// reported. Brief criterion 3 ("no API key present in the client") is therefore
// structural rather than a thing to remember.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, '.env');
const target = join(root, 'app', '.env');

if (!existsSync(source)) {
  console.error('No .env at the repo root. Copy .env.example to .env first.');
  process.exitCode = 1;
} else {
  const lines = readFileSync(source, 'utf8').split(/\r?\n/);
  const kept = [];
  const dropped = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const key = trimmed.slice(0, trimmed.indexOf('=')).trim();
    if (!key) continue;
    (key.startsWith('EXPO_PUBLIC_') ? kept : dropped).push(key);
  }

  const body = lines.filter((l) => l.trim().startsWith('EXPO_PUBLIC_')).join('\n');

  writeFileSync(
    target,
    '# GENERATED by scripts/sync-app-env.mjs — do not edit, do not commit.\n' +
      '# Source of truth is the repo-root .env. Re-run `npm run sync-env` after changing it.\n' +
      '# Only EXPO_PUBLIC_* keys are copied here; everything else is deliberately withheld.\n\n' +
      body +
      '\n'
  );

  console.log(`Wrote app/.env`);
  console.log(`  copied:   ${kept.length ? kept.join(', ') : '(nothing — is .env filled in?)'}`);
  console.log(`  withheld: ${dropped.length ? dropped.join(', ') : '(none)'}`);
}
